[package]
name = "dll-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
libloading = "0.7"
once_cell = "1.13.0"
textcode = "0.2.2"